image: alpine/git

pipelines:
  custom:
    mirror-to-github:
      - step:
          name: Mirror to GitHub
          script:
            # Add GitHub remote
            - git remote add github https://$GITHUB_USERNAME:$GITHUB_TOKEN@github.com/Operator-Syn/peer-tutoring-platform.git
            
            # Fetch all branches and tags
            - git fetch --all
            
            # Push all branches except main
            - for branch in $(git for-each-ref --format='%(refname:short)' refs/heads/); do
                if [ "$branch" != "main" ]; then
                  git push github "$branch";
                fi;
              done
            
            # Push main if it exists locally
            - if git show-ref --verify --quiet refs/heads/main; then
                git push github main;
              fi
            
            # Push all tags
            - git push github --tags