image: alpine/git

pipelines:
  custom:
    mirror-to-github:
      - step:
          name: Mirror to GitHub
          script:
            # Add GitHub remote
            - git remote add github https://$GITHUB_USERNAME:$GITHUB_TOKEN@github.com/Operator-Syn/peer-tutoring-platform.git
            
            # Fetch all branches and tags, create local branches
            - git fetch origin "+refs/heads/*:refs/heads/*" --tags
            
            # Push all branches to GitHub
            - for branch in $(git for-each-ref --format='%(refname:short)' refs/heads/); do
                git push github "$branch";
              done
            
            # Push all tags
            - git push github --tags
