image: alpine/git

pipelines:
  default:
    - step:
        name: Mirror to GitHub
        script:
          - git init
          - git remote add origin https://$BITBUCKET_GIT_HTTP_ORIGIN
          - git remote add github https://$GITHUB_USERNAME:$GITHUB_TOKEN@github.com/Operator-Syn/peer-tutoring-platform.git
          - git fetch origin --prune
          - git push --mirror github