image: alpine/git

pipelines:
  custom:
    mirror-to-github:
      - step:
          name: Mirror to GitHub
          script:
            # Add GitHub remote
            - git remote add github https://$GITHUB_USERNAME:$GITHUB_TOKEN@github.com/Operator-Syn/peer-tutoring-platform.git
            
            # Fetch all branches and tags from Bitbucket
            - git fetch origin "+refs/heads/*:refs/remotes/origin/*" --tags
            
            # Push all branches to GitHub, skip HEAD
            - for branch in $(git for-each-ref --format='%(refname:short)' refs/remotes/origin/); do
                if [ "$branch" != "origin/HEAD" ]; then
                  branch_name=${branch#origin/};
                  git push github "$branch_name";
                fi;
              done
            
            # Push all tags to GitHub
            - git push github --tags
